"""add is_indexd to file model

Revision ID: 3a45b11be31f
Revises: 15a719e3126b
Create Date: 2025-05-07 21:20:05.157562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a45b11be31f'
down_revision: Union[str, None] = '15a719e3126b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_indexed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_indexed')
    # ### end Alembic commands ###
